---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : the-program
production_url : http://zengluyang.github.io

posts:
  permalink: /:permalink/
  summary_lines: 5
  latest: 10

pages:
  permalink: 'pretty'

# <img> tag auto insert config
# %s will be replace by "urlperfix / post name / img filename"
imgs:
  imgtag: '<img src="%s" alt="" width="600">'
  urlperfix: '{{urls.media}}/'
  localdir: 'media/'



